Lc 840 user account pending fix
Civil-Service-Human-Resources/identity-service pull request #200
Opened 2021-02-04 09:45 UTC by jainmangleshco

A fox for user account pending issue.

2021-02-04 09:50 UTC, neeraj-jain-cbo commented
PR has to be created agains the idt-develop branch, not the master branch.

2021-02-05 11:08 UTC, jaylco submitted a review, later dismissed

2021-02-05 11:24 UTC, neeraj-jain-cbo requested changes

2021-02-05 11:32 UTC, jainmangleshco commented on src/main/java/uk/gov/cshr/controller/signup/SignupController.java
> +                    inviteService.updateInviteByCode(pendingInvite.get().getCode(), InviteStatus.EXPIRED);
Ideally the hence part should be part of java code comment anyway i will update it.

2021-02-16 15:06 UTC, neeraj-jain-cbo approved these changes

2021-02-16 15:07 UTC, merged